### ISSUE TITLE
subscribe("snapshot") fails if the assets folder doesn't exist

### ISSUE THREAD

**Issue by yeldarby** [cbartram/Nest#5]
Looks like the culprit is that [saveLatestSnapshot uses the `assets` folder as the default](https://github.com/cbartram/Nest/blob/master/src/index.js#L172) and `saveLatestSnapshot` is used internally by `.subscribe` without a way to override the output directory parameter.

Ideally `subscribe` should probably send the raw image data directly to the callback without having to save it to disk first.

**Comment by cbartram** [comment]
Hi thanks for raising this issue. Let me look into the saving snapshot feature to see if I can address some of these problems.

I think its should be possible to save the latest snapshot data directly to the callback. I will investigate this more.

**Comment by cbartram** [comment]
I just published a new version with a [fix here.](https://www.npmjs.com/package/nest-cam). You can update your code to use the latest version with this: 

```
npm install --save nest-cam@1.0.5
```

There are some other changes that go along with this fix as well. Some of the methods got renamed and there is a separate subscription method for subscribing to snapshots vs regular events.

You can use this demo code (which I tested with a fresh npm install in a separate package) and its working well for me. Let me know if this works for you!

```javascript
const nest = new Nest({
    nestId: "YOUR_NEST_ID",
    clientId: "YOUR_CLIENT_ID",
    refreshToken: "YOUR_REFRESH_TOKEN",
    apiKey: "YOUR_API_KEY"
});

nest.init().then(() => {
    nest.subscribe((eventStream) => {
        console.log('There was some motion or sound caught on the camera!', eventStream);
    });
    // ...or
    nest.getLatestSnapshot().then(image => {
        image.pipe(fs.createWriteStream('/Users/YOUR_USERNAME/nest_test/image_3.jpg'));
    });
    // ... or
    nest.subscribeSnapshot((image) => {
       image.pipe(fs.createWriteStream('/Users/YOUR_USERNAME/nest_test/image_3.jpg'));
    }, (error) => {
        console.log('Oh no there was an error!');
    })
});
```

If this works for you can you close the issue? If not let me know and we can do some more digging!
