### ISSUE TITLE
Can connect to API- cannot download any images

### ISSUE THREAD

**Issue by axwaxw** [cbartram/Nest#6]
Many thanks for this module and for the detailed instructions for obtaining credentials.

I have followed these instructions and I am able to run `nest.getEvents()` successfully to see latest events.

However, I have not been able to run any other function successfully.  

Per the [other issue](https://github.com/cbartram/Nest/issues/5) on this module, it seems that the module writes images to a default directory and if I attempt to run `nest.saveLatestSnapshot()` or `nest.saveSnapshot()`, I get an ENOENT error or 'Not Found' error.  So far, I have been unable to download an image from the API via the module.

My aim is to capture still images from the camera on a periodic basis (approx every minute) in order to create a time-lapse over the long term (approx 4 months).  I had hoped to be able to achieve this with this module.

Any guidance appreciated.

Many thanks again

**Comment by cbartram** [comment]
Hi thanks for raising this issue. Let me look into the saving snapshot feature to see if I can address some of these problems!

**Comment by cbartram** [comment]
I just published a new version with a [fix here.](https://www.npmjs.com/package/nest-cam). You can update your code to use the latest version with this: 

```
npm install --save nest-cam@1.0.5
```

There are some other changes that go along with this fix as well. Some of the methods got renamed and there is a separate subscription method for subscribing to snapshots vs regular events.

You can use this demo code (which I tested with a fresh npm install in a separate package) and its working well for me. Let me know if this works for you!

```javascript
const nest = new Nest({
    nestId: "YOUR_NEST_ID",
    clientId: "YOUR_CLIENT_ID",
    refreshToken: "YOUR_REFRESH_TOKEN",
    apiKey: "YOUR_API_KEY"
});

nest.init().then(() => {
    nest.subscribe((eventStream) => {
        console.log('There was some motion or sound caught on the camera!', eventStream);
    });
    // ...or
    nest.getLatestSnapshot().then(image => {
        image.pipe(fs.createWriteStream('/Users/YOUR_USERNAME/nest_test/image_3.jpg'));
    });
    // ... or
    nest.subscribeSnapshot((image) => {
       image.pipe(fs.createWriteStream('/Users/YOUR_USERNAME/nest_test/image_3.jpg'));
    }, (error) => {
        console.log('Oh no there was an error!');
    })
});
```

**Comment by Juweii** [comment]
Hi @cbartram,
I have the same issue - I am receiving an 404 when trying to access the nest API.
Is nest-cam still working?

Best regards,
Juergen

**Comment by cbartram** [comment]
Hello Juergen,

I just tested the nest-cam package with version 1.0.5 and I was able to successfully receive events from my Nest camera. If you can give me more information about the error like the specific logs and maybe some code snippets of what you are trying to do I may be able to help debug it. Feel free to also create an issue here: https://github.com/cbartram/Nest/issues <https://github.com/cbartram/Nest/issues>

Are you having trouble retrieving your Nest credentials (nestId, refreshToken, apiKey, etc…) or did it suddenly stop working for you?

Sincerely,

Christian
